### ISSUE TITLE
有上传图片的api文档和案列吗？？能不能定时删除所有上传的图片？？kv满了能自动清理吗？

### ISSUE THREAD

**Issue by leioukupo** [Shadownc/CYI-Service#1]

**Comment by Shadownc** [comment]
```
curl -X POST https://your.workers.dev/upload \
  -F "images=@/path/to/image1.jpg" \
  -F "images=@/path/to/image2.png"
```
可选 登录后上传
`-H "Authorization: Bearer $TOKEN" \`
暂时没有定时删除的功能 kv满了不会自动清理

**Comment by leioukupo** [comment]
> ```
> curl -X POST https://your.workers.dev/upload \
>   -F "images=@/path/to/image1.jpg" \
>   -F "images=@/path/to/image2.png"
> ```
> 
> 可选 登录后上传 `-H "Authorization: Bearer $TOKEN" \` 暂时没有定时删除的功能 kv满了不会自动清理

我转python的request写法上传失败啊，有没有python的案例

**Comment by Shadownc** [comment]
```
import requests

url = "https://your.workers.dev/upload"
files = {
    'images': open('/path/to/image1.jpg', 'rb'),
    'images': open('/path/to/image2.png', 'rb')
}

response = requests.post(url, files=files)

print(response.text)
```

**Comment by leioukupo** [comment]
> ```
> import requests
> 
> url = "https://your.workers.dev/upload"
> files = {
>     'images': open('/path/to/image1.jpg', 'rb'),
>     'images': open('/path/to/image2.png', 'rb')
> }
> 
> response = requests.post(url, files=files)
> 
> print(response.text)
> ```

{"code":200,"message":"图片上传完成","uploaded":[],"failed":[{"filename":"1.jpg","reason":"Unsupported file type: "}]}
不行啊

**Comment by Shadownc** [comment]
import requests

url = "https://your.workers.dev/upload"

files = [
    ('images', ('1.png', open('/path/to/1.png', 'rb'), 'image/png')),
    ('images', ('2.jpg', open('/path/to/2.jpg', 'rb'), 'image/jpeg'))
]

response = requests.post(url, files=files)

print(response.text)
